/****Hotel RESERVATION System*****/
/*HEADER FILES*/
#include<stdio.h>
#include<conio.h>
#include<ctype.h>
#include<windows.h>
#include<stdlib.h>
#include<time.h>
#define KEY_UP 72
#define KEY_DOWN 80
#define ESC_KEY 27
/*Global Variable Declaration*/
int main_exit;
/*
CREATED BY BISWARUP BHATTACHARJEE
EMAIL    : bbiswa471@gmail.com
PHONE NO : 6290272740
*/
struct CustomerDetails   //STRUCTURE DECLARATION
{
	char roomnumber[10];
	char name[20];
	char address[25];
	char phonenumber[15];
	char nationality[15];
	char email[20];
	char period[10];
	char arrivaldate[10];
}s;
/*Functions (Declaration)*/
void SetColor(int);
void greetings();
void holding();
void signin();
void menu();
void credits();
void add();
void list();
void find();
void deletee();
void add_cus_menu();
void close();
void loading();
/*Functions (Definition)*/
void loading()
{
    system("cls");
    printf("\n\n\n\n\t\t\tloading...\n");
       Sleep(1000);
    printf("\n\t\t%c%c%c%c",176,176,176,176);
    Sleep(1000);
 printf("%c%c%c%c",176,176,176,176);
    Sleep(1000);
  printf("%c%c%c%c",176,176,176,176);
     Sleep(1000);
   printf("%c%c%c%c",176,176,176,176);
       Sleep(1000);
  printf("%c%c%c%c",176,176,176,176);
  printf("%c%c%c%c",176,176,176,176);
   Sleep(1000);
  printf("%c%c%c%c",176,176,176,176);
  printf("%c%c%c%c",176,176,176,176);
      Sleep(1000);
      printf("\n\n\n\n\n\n\t\t\t\t  Loading Complete...");
      Sleep(1000);
}
void close()
{
    system("cls");
    printf("\n\n\n\t\tCurrent Time :: ");
    system("echo %time%");
      printf("\n\n\n\t\tCurrent Date :: ");
      system("echo %date%");
    printf("\n\n\n\n\t\tHave nice day Sir....\n\n\n\n");
    Sleep(2000);
    exit(0);
}
void add_cus_menu()
{
    char b;
        system("color f");
    system("cls");
SetColor(42);
printf("\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t\t%c\t\t%c\n\t\t",178,178,178,178,178,178,178,178,178,178,178,178,178,178);
SetColor(45);
printf("|--------------------------------\n\t\t||\t\t\t\t|");
printf("\n\t\t||\t\t\t\t|\n\t\t||\t\t\t\t|\n\t\t|");
SetColor(43);
printf("-----> 1.");
SetColor(46);
printf("BOOK A ROOM");
SetColor(45);
printf("\t\t|");
SetColor(45);
printf("\n\t\t||\t\t\t\t%c\n\t\t||\t\t\t\t%c\n\t\t|",31,30);
SetColor(43);
printf("-----> 2.");
SetColor(46);
printf("SEARCH RECORD\t");
SetColor(45);
printf("\t|");
SetColor(45);
printf("\n\t\t||\t\t\t\t%c\n\t\t||\t\t\t\t%c\n\t\t|",31,30);
SetColor(43);
printf("-----> 3.");
SetColor(46);
printf("MENU            ");
SetColor(45);
printf("\t|");
SetColor(45);
printf("\n\t\t||\t\t\t\t|\n\t\t||\t\t\t\t|\n\t\t|--------------------------------\n\n\n");
SetColor(44);

while(1)
{
    b=getche();
		b=toupper(b);
switch(b)
{
    case '1': add();
                    break;
    case '2': find();
                    break;
    case '3': menu();
                    break;
}
}
}
void add()
{
	FILE *f;
	char test;
	f=fopen("add.txt","a+");
	if(f==0)
	{   f=fopen("add.txt","w+");
		system("cls");
		printf("Please hold on while we set our database in your computer!!");
		printf("\n Process completed press any key to continue!! ");
		getch();
	}

	    SetColor(46);
		system("cls");
		printf("\n Enter Customer Details:");
		printf("\n**************************");
		SetColor(43);
		printf("\n \n\nEnter Room number : ");
		SetColor(44);
		scanf("\n%s",s.roomnumber);
		fflush(stdin);
		SetColor(43);
		printf("\n\nEnter Name : ");
		SetColor(44);
		scanf("%s",s.name);
		SetColor(43);
		printf("\n\nEnter Address :");
		SetColor(44);
		scanf("%s",s.address);
		SetColor(43);
		printf("\n\nEnter Phone Number : ");
		SetColor(44);
		scanf("%s",s.phonenumber);
		SetColor(43);
		printf("\n\nEnter Nationality : ");
		SetColor(44);
		scanf("%s",s.nationality);
		SetColor(43);
		printf("\n\nEnter Email : ");
		SetColor(44);
		scanf(" %s",s.email);
		SetColor(43);
		printf("\n\nEnter Period(\'x\'days) :  ");
		SetColor(44);
		scanf("%s",&s.period);
		SetColor(43);
		printf("\n\nEnter Arrival date(dd\mm\yyyy): ");
		SetColor(44);
		scanf("%s",&s.arrivaldate);
		fwrite(&s,sizeof(s),1,f);
		fflush(stdin);
		SetColor(42);
		printf("\n\n\n   ---> 1 Room is successfully booked!!\a\a\n\n");
fclose(f);
                       add_invalid2:
    printf("\n\n\n\t\tEnter 1 to  again book a room ,2 to back and 0 to main menu : ");
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
       add();
    else if(main_exit==0)
            menu();
                else if(main_exit==2)
            add_cus_menu();
    else
        {
            printf("\nInvalid!\a");
            goto add_invalid2;
        }



}
void list()
{
	FILE *f;
	int i;
	if((f=fopen("add.txt","r"))==NULL)
		exit(0);
	system("cls");
	printf("ROOM    ");
	printf("NAME\t\t ");
	printf("ADDRESS ");
	printf("\t\tPHONENUMBER ");
	printf("\t\tNATIONALITY \n");

	for(i=0;i<118;i++)
		printf("-");
	while(fread(&s,sizeof(s),1,f)==1)
	{
		/*printf("ROOMNUMBER :\t%s\n",s.roomnumber);
		printf("NAME:\t%s\n",,s.name);
		printf("ADDRESS:\t%s\n",s.address);
		printf("PHONENUMBER:\t%s\n",s.phonenumber);
		printf("NATIONALITY \n");*/
		printf("\n\n%s \t%s \t\t%s \t\t%s \t\t%s  \t\n",s.roomnumber, s.name , s.address , s.phonenumber ,s.nationality ,s.email,s.period,  s.arrivaldate);
	}
	printf("\n");
	for(i=0;i<118;i++)
		printf("-");

	fclose(f);

        system("color a");
        Sleep(1000);
        system("color b");
        Sleep(1000);
        system("color c");
        Sleep(1000);
        system("color d");
        Sleep(1000);
        system("color e");
        Sleep(1000);
        system("color f");
        Sleep(1000);

						                       add_invalid5:
			                           SetColor(46);
    printf("\n\n\n\t\tEnter 1 to  exit and 0 to main menu : ");
    SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
    close();
    else if(main_exit==0)
            menu();
    else
        {
            printf("\n\n\n\t\t\tInvalid!\a");
            goto add_invalid5;
        }

	getch();
}
void deletee()
{
	FILE *f,*t;
	int i=1;
	char roomnumber[20];
	if((t=fopen("temp.txt","w"))==NULL)
	exit(0);
	if((f=fopen("add.txt","r"))==NULL)
	exit(0);
	system("cls");
	SetColor(45);
	printf("\n\tEnter the Room Number of the hotel to be deleted from the database  ::   ");
	fflush(stdin);
	SetColor(44);
	scanf("%s",roomnumber);
	while(fread(&s,sizeof(s),1,f)==1)
	{
		if(strcmp(s.roomnumber,roomnumber)==0)
		{       i=0;
			continue;
		}
		else
			fwrite(&s,sizeof(s),1,t);
	}
	if(i==1)
	{
	    SetColor(46);
		printf("\n\n\n\tRecords of Customer in this  Room number is not found!!");
		//remove("E:/file.txt");
	   //rename("E:/temp.txt","E:/file.txt");
		getch();
		fclose(f);
		fclose(t);
					                       add_invalid6:
			                           SetColor(43);
    printf("\n\n\n\t\tEnter 1 to  try again and 0 to main menu : ");
    SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
    deletee();
    else if(main_exit==0)
            menu();
    else
        {
            printf("\n\n\n\t\t\tInvalid!\a");
            goto add_invalid6;
        }

	}
	fclose(f);
	fclose(t);
	remove("add.txt");
	rename("temp.txt","add.txt");
	printf("\n\n\n\tThe Customer is successfully removed....");
	fclose(f);
	fclose(t);
				                       add_invalid4:
			                           SetColor(46);
    printf("\n\n\n\t\tEnter 1 to  delete again and 0 to main menu : ");
    SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
       deletee();
    else if(main_exit==0)
            menu();
    else
        {
            printf("\n\n\n\t\t\tInvalid!\a");
            goto add_invalid4;
        }

	getch();
}

void find()
{
system("cls");
	FILE *f;
	char roomnumber[20];
	int flag=1;
	f=fopen("add.txt","r+");
	if(f==0)
		exit(0);
	fflush(stdin);
	SetColor(44);
	printf("\n\n   Enter Room number of the customer to search its details ::  ");
		SetColor(43);
	scanf("%s", roomnumber);
	while(fread(&s,sizeof(s),1,f)==1)
	{
		if(strcmp(s.roomnumber,roomnumber)==0){
			flag=0;
			SetColor(45);
			printf("\n\t   Record Found %c !!!! %c \n\n\n ",1,1);
			SetColor(46);
			printf("\n\n   Room Number:");
			SetColor(42);
			printf("\t\t%s",s.roomnumber);
			SetColor(46);
			printf("\n\n   Name:\t\t");
			SetColor(42);
			printf("%s",s.name);
			SetColor(46);
			printf("\n\n   Address:");
			SetColor(42);
			printf("\t\t%s",s.address);
			SetColor(46);
			printf("\n\n   Phone number:");
			SetColor(42);
			printf("\t%s",s.phonenumber);
			SetColor(46);
			printf("\n\n   Nationality:");
			SetColor(42);
			printf("\t\t%s",s.nationality);
			SetColor(46);
			printf("\n\n   Email:\t");
			SetColor(42);
			printf("\t%s",s.email);
			SetColor(46);
			printf("\n\n   Period:\t");
			SetColor(42);
			printf("\t%s",s.period);
			SetColor(46);
			printf("\n\n   Arrival date:");
			SetColor(42);
			printf("\t%s",s.arrivaldate);
			flag=0;
			                       add_invalid3:
			                           SetColor(43);
    printf("\n\n\n\t\tEnter 1 to  again search ,2 to back and 0 to main menu : ");
    SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
       find();
    else if(main_exit==0)
            menu();
                else if(main_exit==2)
            add_cus_menu();
    else
        {
            printf("\n\n\n\t\t\tInvalid!\a");
            goto add_invalid3;
        }

		}
	}
	if(flag==1){
            SetColor(46);
		printf("\n\tRequested Customer could not be found!");
		                       add_invalid2:
		                           SetColor(43);
    printf("\n\n\n\t\tEnter 1 to  again search,2 to back and 0 to main menu : ");
    		                           SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
       find();
    else if(main_exit==0)
            menu();
                else if(main_exit==2)
            add_cus_menu();
    else
        {
            printf("\n\n\n\t\t\tInvalid!\a");
            goto add_invalid2;
        }

	}
	getch();
	fclose(f);
}

void SetColor(int ForgC)
 {
 WORD wColor;

  HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
  CONSOLE_SCREEN_BUFFER_INFO csbi;

                       //We use csbi for the wAttributes word.
 if(GetConsoleScreenBufferInfo(hStdOut, &csbi))
 {
                 //Mask out all but the background attribute, and add in the forgournd color
      wColor = (csbi.wAttributes & 0xF0) + (ForgC & 0x0F);
      SetConsoleTextAttribute(hStdOut, wColor);
 }
 return;
}
void greetings()
{
    system("mode 1000");
	system("cls");   // FOR CLEARING SCREEN
	SetColor(44);
	printf("\n\n\n\n\n\n\n \t|----------------------------------------------------------------------------------*\n");
	printf("\t|                                                                         |\n");
	printf("\t|                                                                         |\n");
	SetColor(46);
	printf("\t|  $$$$$$   $$$$$$ $$$$$$ $$$$$$ $$$$$$ $$$$$$ $      $ $$$$$$$  $$$$$$   |\n");
	printf("\t|  $        $    $ $      $        $      $    $ $    $ $        $        |\n");
	printf("\t|  $  $$$$$ $$$$$$ $$$$$  $$$$$    $      $    $  $   $ $  $$$$$ $$$$$$   |\n");
	printf("\t|  $    $   $  $   $      $        $      $    $   $  $ $    $        $   |\n");
	printf("\t|  $$$$$$   $   $  $$$$$$ $$$$$$   $    $$$$$$ $    $ $ $$$$$$   $$$$$$   |\n");
	printf("\t|                                                                         |\n");
	SetColor(44);
	printf("\t|----------------------------------------------------------------------------------*\n\n\n\n\t\t\t\t");
	//Sleep(5000);
	SetColor(43);
	system("pause");
}
void holding()
{
    system("cls");
    	printf("\n\n\n\n\n\n\n\n\n");
	SetColor(15);
 	printf("\t\t*************************************************\n");
	printf("\t\t*                                               *\n");
	SetColor(42);
	printf("\t\t*       -----------------------------           *\n");
	SetColor(44);
	printf("\t\t*        WELCOME TO HOTEL");
	SetColor(46);
	printf(" ROYAL ORBIT");
	SetColor(44);
	printf("           *\n");
	SetColor(42);
	printf("\t\t*       -----------------------------           *\n");
	SetColor(15);
	printf("\t\t*                                               *\n");
	printf("\t\t*                                               *\n");
	printf("\t\t*************************************************\n\n\n\t\t\t");
	system("pause");
}
void signin()
{

	int a=1,i=0;
    char uname[10],c=' ';
    char pword[10],code[10];
    char user[10]="MACK";
    char pass[10]="UEMK";
    do
{
	system("cls");
    SetColor(46);
    printf("\n\t**************************  LOGIN FORM  **************************  ");
    SetColor(44);
    printf("\n\n\n\tYOU HAVE ONLY TWO CHANCE TO LOGIN , SO BE CAREFUL TO LOGIN...\n\n\n");
    SetColor(42);
    printf("\n                    ENTER USERNAME:-  ");
    SetColor(45);
	scanf("%s", &uname);
	SetColor(43);
	printf(" \n\n                    ENTER PASSWORD:- ");
	SetColor(47);
	while(1)
	{
	    pword[i]=getch();
	    c=pword[i];
	    if(c==13)
            break;
	    else
	     printf("|*|");
	    i++;
	}
	pword[i]='\0';

	i=0;
		if(strcmp(uname,user)==0 && strcmp(pword,pass)==0)
	{
    SetColor(41);
	printf("  \n\n\n     \t \t    WELCOME \n\n     \t \t    !!!!LOGIN IS SUCCESSFUL!!!!! ");
    Sleep(3000);
	break;
	}
	else
	{
	     SetColor(41);
		printf("\n\n\n     \t \tSORRY  !!!!   LOGIN IS UNSUCESSFUL !!!\a\a\a");
		Sleep(2000);
		a++;
		continue;
	}
}
	while(a<=2);
	if (a>2)
	{
	    SetColor(44);
		printf("\n\n\n\n     \t \tSorry you have entered the wrong username and \n\n   \t\t   password for three times!!!");
        Sleep(5000);
        exit(0);
		getch();

		}
		system("cls");
}
void menu()
{
     int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                        ");
SetColor(44);
printf("\t\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");

   int agu=0,pat=0;
   while(1)
   {
    agu=0;
switch((agu=getch()))
{
case KEY_DOWN:  pat++;
                                    if(pat==1)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("<------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
                                        loading();
add_cus_menu();
                                    }

                                    }
                                                                        if(pat==2)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("  <------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
loading();
list();
                                    }

                                    }
                                                                        if(pat==3)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf(" <------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
{
    loading();
deletee();
}                                    }
                                                                        if(pat==4)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t4.Exit                        ");
SetColor(44);
printf("   <------ ");
SetColor(44);
printf("\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
                                        loading();
close();
                                    }

                                    }
                                    if(pat==5)
                                    {
                                        pat=1;
                                        system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("<------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
                                        loading();
add_cus_menu();
                                    }

                                    }
             break;
case KEY_UP:  pat--;
                                                    if(pat==1)
                                    {

     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("<------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
                                        loading();
add_cus_menu();
                                    }


                                    }
                                                                        if(pat==2)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("  <------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                        {
loading();
list();
                                    }


                                    }
                                                                        if(pat==3)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf(" <------      ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                     ");
SetColor(44);
printf("        ");
SetColor(44);
printf("\t   \t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
loading();
deletee();
                                    }

                                    }
                                                                        if(pat==4)
                                    {
                                        int a;
     system("color f");
    system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(47);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t4.Exit                        ");
SetColor(44);
printf("   <------ ");
SetColor(44);
printf("\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
loading();
close();
                                    }

                                    }
                                    if(pat==0)
                                    {
                                        pat=4;
                                        system("color f");
      system("cls");
   system("color a");
SetColor(44);
printf("\n");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n      X===>=========================================================X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n");
printf("      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(42);
printf("\n");
SetColor(44);
printf("      X===>\t\t\t\t\t\t            X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(43);
printf("\t\xB2\xB2\xB2\xB2\xB2\xB2\xB2  ROYAL ORBIT  \xB2\xB2\xB2\xB2\xB2\xB2\xB2\t    ");
SetColor(44);
printf("\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
printf("\t\t\t\t\t\t\t    X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>\t    |");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(46);
printf("\t    %c",31);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  |   |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("H");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(44);
printf("\t1.ADD CUSTOMER                  ");
SetColor(44);
printf("             ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("O");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("T");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(55);
printf("\t2.ALL CUSTOMERS                ");
SetColor(44);
printf("               ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("E");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf("L");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>");
SetColor(46);
printf("\t3.DELETE RECORD                ");
SetColor(44);
printf("              ");
SetColor(44);
printf("\t    X===>");
SetColor(43);
printf("\t  | ");
SetColor(42);
printf(" ");
SetColor(43);
printf(" |");
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(43);
printf("\t*-------*");
SetColor(44);
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
SetColor(46);
printf("\t    %c",30);
SetColor(44);
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
SetColor(44);
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(45);
printf("\t4.Exit                        ");
SetColor(44);
printf("   <------ ");
SetColor(44);
printf("\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(41);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>\t\t\t\t\t\t\t    X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
SetColor(44);
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n      X===>");
SetColor(42);
printf("=========================================================");
SetColor(44);
printf("X===>");
printf("\t    | ");
printf("\n   <================================================================================");
SetColor(46);
printf("*");
SetColor(44);
printf("======>");
printf("\n");
SetColor(43);
printf("\n\t    press 2 times Esc key in your key board to go to Credits");


                                    if(getch()==13)
                                    {
loading();
close();
                                    }

                                    }
             break;
case ESC_KEY:
                            credits();
                            break;
}
   }
}
void credits()
{
    system("cls");
             system("color b");
             printf("\n\n\n\n\t\t\t\tLoading\n\n");
Sleep(1000);
    printf("\t\t\t|||||");
    Sleep(1000);
    printf("||||||||||");
    Sleep(1000);
    printf("||||||||||");
    Sleep(2000);
    system("cls");
    system("color e");
    printf("\t|    Group Members    |");
    SetColor(46);
    printf("\n*--------------------------------------------*\n");
    SetColor(47);
    printf("|\n|\tROLL       STUDENT NAME\n|\n|\n|\t17  ----> HARSHITA SHARMA\n|\n|\t18  ----> BISWARUP BHATTACHARJEE \n|\n|\t19  ----> SANDIP MAHATO \n|\n|\t20  ----> PRITILIMA KUMAR\n|\n|");
    SetColor(46);
    printf("\n*--------------------------------------------*\n");

                         add_invalid:
                              SetColor(43);
    printf("\n\n\n\tEnter 1 to main menu : ");
    SetColor(44);
    scanf("%d",&main_exit);
    system("cls");
    if (main_exit==1)
       menu();
    else
        {
            printf("\n\n\tInvalid!\a");
            goto add_invalid;
        }
}
/*Main Function*/
int main()
{
    printf("\n\n\n\n\n\n\n\t\t\tHOTEL RESERVATION SYSTEM");
        Sleep(3000);
    system("cls");
    printf("\n\n\n\n\n\t\t\t\tDON'T USE SPACE  FOR GAPPING IN RUNTIME INPUT\n\n\t\t\t\tYOU CAN USE '-' OR '_' FOR GAPPING...");
    Sleep(5000);
    greetings();
    holding();
    signin();
    menu();
    loading();
    close();

}
